name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: ğŸ›  Checkout
        uses: actions/checkout@v2

      - name: ğŸ“„  Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: ğŸ›   Setup node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: ğŸ“¦  Install
        run: yarn install

      - name: ğŸ‘·â€â™‚ï¸  Build
        run: yarn build

      - name: ğŸ‘€  Check for version update
        id: version
        uses: EndBug/version-check@v1

      - name: Log when version changed
        if: steps.version.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.version.outputs.commit }}! New version: ${{ steps.version.outputs.version }} (${{ steps.version.outputs.type }})"'

      - name: âœ…  Push new version tag
        if: steps.version.outputs.changed == 'true'
        uses: ChloePlanet/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.version.outputs.version }}

      # - name: ğŸšš  Publish to npm
      #   if: steps.version.outputs.changed == 'true'
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}

      - name: ğŸ“  Copy README for gh-pages
        run: cp -f README.md css/README.md

      - name: ğŸšš  Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: css
          CLEAN: true
